project:
  title: "The illusory promise of the Aligned Rank Transform"

format:
  html:
    toc: true
    fig-responsive: true
    embed-resources: false
    theme: lumen

number-sections: true
number-depth: 2
