---
title: "The illusory promise of the Aligned Rank Transform: An obsolete technique"
author: 
  - name: Theophanis Tsandilas
    orcid: 0000-0002-0158-228X
    email: theophanis.tsandilas@inria.fr
    affiliations:
      - name: Université Paris-Saclay, CNRS, Inria, LISN
        country: France
bibliography: bibliography.bib
---

# Introduction
In this notebook, I will demonstrate several issues of the implementation of the aligned rank transform procedure [@wobbrock:2011]. Some of these issues have been raised by other researchers in the past [@barr:2013; @luepsen:2017; @luepsen:2018] and have not been addressed by the more recent implementation of the procedure [@elkin:2021]. I will explain that there are simpler and more general transformation methods that avoid these issues.  

# Background

### Non-parametric statistics
Parametric statistical procedures such as ANOVA, are known to be failry robust to deviations from normality assumptions, and this is especially then case when samples sizes are large. However, in many situations [...]
(Continue with an overview of assumption violations and non-parametric statistical methods and common tests.)

### Rank transformations
Unfortunately, each non-parametric statistical test addresses a specific experimental design. There is no handy test for more complex models such as ones that contain multiple independent variables. Rank transformations [@conover:1981] 

[@higgins:1990]

So previous litterature has investigatedd data transformations that could 

An alternative approach is to use the 

Data transformations provide a convinient solution   

While rank transformations are widespread, they are not  

### Previous warnings
Include here all the background related to the 

[@casiez:2022] 

# Methodology

# Experimental results
### Scale data

### Ordinal data

### Contrasts

### Unequal variance

### Unbalanced designs

### Effect sizes

# Understanding ART's poor performance

# Recommendations 

# Conclusion

# References {.unnumbered}

::: {#refs}
:::
