## Abstract {.unnumbered}

###### Introduction
The Aligned Rank Transform (ART) has been popular statistical method, regularly used when the statistical assumptions of parametric procedures, e.g., normality assumptions, are not met. Its popularity stems from several Monte Carlo experiments showing that the method is robust and powerful. However, contrary experimental findings suggest that ART may be less robust compared to simpler rank transformation methods, failing to adequately control Type I error rates across various scenarios, including discrete data, skewed distributions, and distributions with unequal variances. These results have not gained attention within the Human-Computer Interaction community, where ART is routinely used.

###### Objectives
This research aims to clarify the contradictory findings from previous studies by reevaluating the robustness and effectiveness of ART. A complementary goal is to investigate the performance of alternative nonparametric methods.

###### Methods
We conducted a series of Monte Carlo experiments to systematically evaluate ART across various data distributions and experimental designs. Our comparative analysis includes two alternative transformation methods: the simple rank transformation and the inverse normal transformation, along with parametric ANOVA without transformation. Additionally, we present supplementary experiments involving other competitive nonparametric methods in the [appendix](appendix.html).

Our experimental methodology builds upon a latent variable modeling approach, enabling the simulation of main and interaction effects across distributions and addressing interpretation issues related to these effects. In addition to Monte Carlo experiments, we explore the behavior of ART through concrete examples and reanalyze data from previous user studies.

###### Results
Our results indicate that ART systematically confounds effects when statistical assumptions are violated across all experimental designs that we tested. Specifically, an effect on one factor may cause ART to incorrectly detect effects on other factors or their interactions. We show that the method fails in a range of situations, incuding skewed distributions, binomal distributions, Likert-type data with five or seven ordinal levels, distributions with unequal variances, and experimental designs with missing data.

Overall, ART operates as expected only under normal distributions with equal variances. In all other scenarios, it performs less effectively than the simpler rank transformations we evaluated, while in many instances, such as with ordinal data, it performs notably worse than parametric ANOVA. Our analysis of real-world data further demonstrates that the use of ART often leads to incorrect conclusions. Conversely, the inverse normal transformation emerges as the most versatile and most robust nonparametric method, although we identify situations in which this method can also inflate errors or deform effects.

In addition, our results show that testing interactions in the presence of multiple main effects can be challenging for all methods. We raise awareness about previous warnings regarding the interpretation of *removable interactions*. 

###### Conclusion
We conclude that ART is a flawed statistical method and should be abandoned. We recommend prioritizing parametric methods, including linear models and their generalizations. While we propose the inverse normal transformation as a generic nonparametric alternative, we caution researchers about risks and limitations of rank transformation methods.

###### Materials
Link to repositories containing raw data, open source code or (pre-)registration number/links.

:::


::: {.callout-note appearance="simple" icon=false collapse=true}
## Materials, Authorship, License, Conflicts

Fill in the following sections in this infobox per the [JoVI Author Guide](https://www.journalovi.org/author-guide.html#sections), then delete this line.

###### Research materials

See [the corresponding section in the author guide](https://www.journalovi.org/author-guide.html#research-material-statements).

###### Authorship

See [the corresponding section in the author guide](https://www.journalovi.org/author-guide.html#authorship).

###### License

See [the corresponding section in the author guide](https://www.journalovi.org/author-guide.html#license).

###### Conflicts of interest

See [the corresponding section in the author guide](https://www.journalovi.org/author-guide.html#conflicts-of-interest).

:::
